// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { GameHouse$Type } from "./GameHouse";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GameHouse"]: GameHouse$Type;
    ["contracts/house/GameHouse.sol:GameHouse"]: GameHouse$Type;
  }
}
