// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { TexasHoldem$Type } from "./TexasHoldem";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TexasHoldem"]: TexasHoldem$Type;
    ["contracts/games/TexasHoldem.sol:TexasHoldem"]: TexasHoldem$Type;
  }
}
