// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { RunningGame$Type } from "./RunningGame";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RunningGame"]: RunningGame$Type;
    ["contracts/games/RunningGame.sol:RunningGame"]: RunningGame$Type;
  }
}
