// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Dealer$Type } from "./Dealer";
import { IGame$Type } from "./IGame";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Dealer"]: Dealer$Type;
    ["IGame"]: IGame$Type;
    ["contracts/house/Dealer.sol:Dealer"]: Dealer$Type;
    ["contracts/house/Dealer.sol:IGame"]: IGame$Type;
  }
}
