// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { GameHouseToken$Type } from "./GameHouseToken";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["GameHouseToken"]: GameHouseToken$Type;
    ["contracts/token/GameHouseToken.sol:GameHouseToken"]: GameHouseToken$Type;
  }
}
