// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { IRunningGameMetadata$Type } from "./IRunningGameMetadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IRunningGameMetadata"]: IRunningGameMetadata$Type;
    ["contracts/games/IRunningGameMetadata.sol:IRunningGameMetadata"]: IRunningGameMetadata$Type;
  }
}
