// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IRunningGameMetadata$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "IRunningGameMetadata",
  "sourceName": "contracts/games/IRunningGameMetadata.sol",
  "abi": [
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "runningGameId",
          "type": "uint256"
        }
      ],
      "name": "RunningGameCreated",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "runningGameId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "enum IRunningGameMetadata.RunningGameStatus",
          "name": "status",
          "type": "uint8"
        }
      ],
      "name": "RunningGameStatusChanged",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "uint256",
          "name": "runningGameId",
          "type": "uint256"
        },
        {
          "indexed": false,
          "internalType": "address",
          "name": "winner",
          "type": "address"
        }
      ],
      "name": "RunningGameWon",
      "type": "event"
    }
  ],
  "bytecode": "0x",
  "deployedBytecode": "0x",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IRunningGameMetadata",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRunningGameMetadata$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/games/IRunningGameMetadata.sol:IRunningGameMetadata",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IRunningGameMetadata$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IRunningGameMetadata",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRunningGameMetadata$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/games/IRunningGameMetadata.sol:IRunningGameMetadata",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IRunningGameMetadata$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IRunningGameMetadata",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRunningGameMetadata$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/games/IRunningGameMetadata.sol:IRunningGameMetadata",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IRunningGameMetadata$Type["abi"]>>;
}
