// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Cashier$Type } from "./Cashier";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Cashier"]: Cashier$Type;
    ["contracts/house/Cashier.sol:Cashier"]: Cashier$Type;
  }
}
