// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { Blackjack$Type } from "./Blackjack";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Blackjack"]: Blackjack$Type;
    ["contracts/games/Blackjack.sol:Blackjack"]: Blackjack$Type;
  }
}
